kumano: Add Xperia 1/5 Kumano platform
mer-hybris/droid-system-sony-template pull request #8
Opened 2021-11-19 17:44 UTC by Thaodan

2021-11-29 20:09 UTC, voidanix approved these changes
Please add the  in the file name for the bahamut models (e.g. ), the rest LGTM

2021-12-07 08:29 UTC, sledges requested changes
What @voidanix said:)

2021-12-07 08:46 UTC, Thaodan commented
> @sledges requested changes on this pull request.
> 
> What @voidanix said:)
Already fixed.

2021-12-07 08:55 UTC, sledges approved these changes

2021-12-07 09:05 UTC, merged